apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-hello
  labels:
    app: rs-app-hello
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello-container
          image: busybox
          command: ['sh', '-c', 'echo Hello from my container! && sleep 3600']
